{% set version = "0.6.1" %}

package:
  name: ffi-navigator
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/ffi-navigator/ffi_navigator-{{ version }}.tar.gz
  sha256: 46b4afed44a3e8dade53f33db0cda70fdbd5a19da1e2b78fb2b2b20ce4b5d0e9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - attrs
    - python >={{ python_min }}
    - python-jsonrpc-server

test:
  imports:
    - ffi_navigator
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tqchen/ffi-navigator
  summary: Language server for navigating FFI calls
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
