{% set version = "0.6.3" %}

package:
  name: ffi-navigator
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/ffi-navigator/ffi_navigator-{{ version }}.tar.gz
  sha256: ce12a02719f11908e0b79c36cf3a5ff2de2e58b7e2eba51f335eb7784cfcb5d9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - attrs
    - python >={{ python_min }}
    - python-jsonrpc-server

test:
  imports:
    - ffi_navigator
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tqchen/ffi-navigator
  summary: Language server for navigating FFI calls
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
